import { TemplateType } from "@motionly/base";

export const yir: TemplateType = {
  duration: 10,
  fps: 30,
  height: 480,
  width: 854,
  comps: [
    {
      comp: "image",
      objectFit: "cover",
      src: "https://picsum.photos/seed/hdssddssgdsdsd/1920/1080",
      id: "qs0uxd",
      x: 0,
      y: 0,
      borderRadius: 0,
      duration: 0,
      from: 0,
      rotation: 0,
      animations: [
        {
          prop: "scale",
          type: "interpolate",
          start: 0,
          from: 1,
          to: 1.5,
          duration: 0,
        },
      ],
    },
    {
      comp: "div",
      bg:{
        type: "basic",
        color: "#FFFFFFFF",
      },
      comps: [
        {
          comp: "image",
          objectFit: "cover",
          src: "https://motionly-media.s3.amazonaws.com/clcl1mck50000mf0816lo9n01/qRxbC9Xq_400x400.jpg",
          id: "4e5o7ef",
          x: 92.07682750000029,
          y: 153.45257609999996,
          width: 148,
          height: 148,
          borderRadius: 1000,
          duration: 0,
          from: 0,
          rotation: 0,
          animations: [
            {
              prop: "translateY",
              type: "spring",
              start: 0.1,
              from: 1000,
              to: 0,
              duration: 0,
              mass: 1,
              damping: 14,
              stiffness: 80,
            },
            {
              prop: "translateY",
              type: "spring",
              start: -1,
              from: 0,
              to: -1000,
              duration: 0,
              mass: 1,
              damping: 14,
              stiffness: 80,
            },
          ],
        },
        {
          comp: "text",
          textStyle: {
            bg: {
              type: "basic",
              color: "#FFFFFFFF",
            },
            color:{
              type: "basic",
              color: "#FFFFFFFF",
            },
            fontSize: 70,
            fontFamily: "Arial",
            fontWeight: 700,
            textAlign: "left",
          },
          text: "Hi Gary!",
          id: "bkfjwrr",
          x: 275.6039287000002,
          y: 175.61125290000052,
          width: 285,
          height: 101,
          borderRadius: 0,
          duration: 0,
          from: 0,
          rotation: 0,
          animations: [
            {
              prop: "translateY",
              type: "spring",
              start: 0.3,
              from: 1000,
              to: 0,
              duration: 0,
              mass: 1,
              damping: 14,
              stiffness: 80,
            },
            {
              prop: "translateY",
              type: "spring",
              start: -0.8,
              from: 0,
              to: -1000,
              duration: 0,
              mass: 1,
              damping: 14,
              stiffness: 80,
            },
          ],
        },
        {
          comp: "text",
          textStyle: {
            bg: {
              type: "basic",
              color: "#FFFFFFFF",
            },
            color: {
              type: "basic",
              color: "#FFFFFFFF",
            },
            fontSize: 50,
            fontFamily: "Arial",
            fontWeight: 700,
            textAlign: "center",
          },
          text: "Here's how your year went",
          id: "2iiiy5rh",
          x: 0.21262210000000137,
          y: 326.35366899999997,
          width: 854,
          height: 99,
          borderRadius: 0,
          duration: 0,
          from: 0.005244779992922024,
          rotation: 0,
          animations: [
            {
              prop: "translateY",
              type: "spring",
              start: 0.5,
              from: 1000,
              duration: 0,
              mass: 1,
              damping: 14,
              stiffness: 80,
            },
            {
              prop: "translateY",
              type: "spring",
              start: -0.6,
              from: 0,
              to: -1000,
              duration: 0,
              mass: 1,
              damping: 14,
              stiffness: 80,
            },
          ],
        },
      ],
      id: "d0s9ywc",
      x: 0,
      y: 0,
      borderRadius: 0,
      duration: 6.694433319983981,
      from: 0,
      rotation: 0,
      animations: [],
    },
    {
      comp: "div",
      bg: {
        type: "basic",
        color: "#FFFFFFFF",
      },
      comps: [
        {
          comp: "text",
          textStyle: {
            color: {
              type: "basic",
              color: "#FFFFFFFF",
            },
            fontSize: 60,
            fontFamily: "Arial",
            fontWeight: 700,
            textAlign: "center",
            lineHeight: 1.3,
            outlineWidth: 10,
          },
          text: "You were killing it",
          id: "iqmg066",
          x: 0.7753749000000028,
          y: 86.09441539999995,
          width: 855,
          height: 83,
          borderRadius: 0,
          duration: 0,
          from: 0,
          rotation: 0,
          animations: [
            {
              prop: "translateX",
              type: "spring",
              from: -1000,
              duration: 0,
              mass: 1,
              damping: 14,
              stiffness: 80,
            },
          ],
        },
        {
          comp: "graph",
          type: "bar",
          src: [
            2, 5, 2, 9, 5, 3, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20,
          ],
          color: {
            type: "basic",
            color: "#FFFFFFFF",
          },
          gap: 3,
          roundness: 10,
          animationDuration: 2,
          animationStart: 0,
          id: "kpgtitd",
          x: 0.29513340000000454,
          y: 148.969991,
          width: 854,
          height: 331,
          borderRadius: 0,
          duration: 0,
          from: 0,
          rotation: 0,
          animations: [],
        },
      ],
      id: "sobonvc",
      x: 0,
      y: 0,
      borderRadius: 0,
      duration: 6.156187424909892,
      from: 6.757592843865158,
      rotation: 0,
      animations: [],
    },
    {
      comp: "text",
      textStyle: {
        bg: {
          type: "basic",
          color: "#FFFFFFFF",
        },
        color: {
          type: "basic",
          color: "#FFFFFFFF",
        },
        fontSize: 40,
        fontFamily: "Inter",
        fontWeight: 700,
        textAlign: "left",
      },
      text: "Year in Review - Year in Review - Year in Review - Year in Review - Year in Review - Year in Review -  Year in Review - Year in Review ",
      id: "7ayy8qp",
      x: 0,
      y: 0,
      width: 4000,
      height: 60,
      borderRadius: 0,
      duration: 0,
      from: 0,
      rotation: 0,
      animations: [
        {
          prop: "translateX",
          type: "interpolate",
          from: 0,
          to: -1000,
          duration: 0,
        },
      ],
    },
  ],
};
