import { ComponentProps } from "@motionly/base";

export const components: ComponentProps[] = [
  {
    id: "r81ebs",
    comp: "image",
    height: 1080,
    width: 1080,
    x: 0,
    y: 0,
    objectFit: "cover",
    borderRadius: 10,
    src: "https://picsum.photos/seed/dsdfddf/1080/1080",
    from: 0,
    duration: 0,
    rotation: 0,
  },
  {
    comp: "video",
    objectFit: "cover",
    startFrom: 0,
    src: "https://remotionlambda-24lixyhuqn.s3.us-east-1.amazonaws.com/video.mp4",
    muted: false,
    volume: 100,
    id: "dgrplp4",
    x: 0,
    y: 300,
    width: 1080,
    height: 500,
    borderRadius: 0,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [],
  },
  {
    comp: "transcription",
    height: 275,
    src: [
      {
        text: "If",
        start: 0.16,
        end: 0.32,
      },
      {
        text: "you",
        start: 0.36,
        end: 0.56,
      },
      {
        text: "only",
        start: 0.6,
        end: 0.92,
      },
      {
        text: "have",
        start: 1,
        end: 1.32,
      },
      {
        text: "24",
        start: 1.4,
        end: 2.04,
      },
      {
        text: "hours",
        start: 2.12,
        end: 2.36,
      },
      {
        text: "in",
        start: 2.44,
        end: 2.6,
      },
      {
        text: "a",
        start: 2.64,
        end: 2.72,
      },
      {
        text: "day,",
        start: 2.72,
        end: 3.28,
      },
      {
        text: "your",
        start: 3.44,
        end: 3.84,
      },
      {
        text: "success",
        start: 3.88,
        end: 4.4,
      },
      {
        text: "is",
        start: 4.52,
        end: 4.8,
      },
      {
        text: "dependent",
        start: 4.84,
        end: 5.28,
      },
      {
        text: "upon",
        start: 5.28,
        end: 5.76,
      },
      {
        text: "how",
        start: 5.84,
        end: 6.04,
      },
      {
        text: "you",
        start: 6.08,
        end: 6.2,
      },
      {
        text: "use",
        start: 6.24,
        end: 6.4,
      },
      {
        text: "the",
        start: 6.44,
        end: 6.6,
      },
      {
        text: "24.",
        start: 6.64,
        end: 7.44,
      },
      {
        text: "You",
        start: 8.2,
        end: 8.52,
      },
      {
        text: "got",
        start: 8.56,
        end: 8.68,
      },
      {
        text: "to",
        start: 8.72,
        end: 8.8,
      },
      {
        text: "hear",
        start: 8.8,
        end: 8.92,
      },
      {
        text: "me.",
        start: 8.96,
        end: 9.08,
      },
      {
        text: "People",
        start: 9.12,
        end: 9.28,
      },
      {
        text: "talk",
        start: 9.32,
        end: 9.48,
      },
      {
        text: "about",
        start: 9.52,
        end: 9.68,
      },
      {
        text: "Oprah",
        start: 9.72,
        end: 10,
      },
      {
        text: "Winfrey.",
        start: 10,
        end: 10.56,
      },
      {
        text: "You",
        start: 10.64,
        end: 10.8,
      },
      {
        text: "know,",
        start: 10.8,
        end: 10.96,
      },
      {
        text: "Ted",
        start: 11,
        end: 11.28,
      },
      {
        text: "Turner,",
        start: 11.32,
        end: 11.84,
      },
      {
        text: "Warren",
        start: 11.92,
        end: 12.32,
      },
      {
        text: "Buffett.",
        start: 12.36,
        end: 12.8,
      },
      {
        text: "Listen",
        start: 12.8,
        end: 12.96,
      },
      {
        text: "to",
        start: 13,
        end: 13.2,
      },
      {
        text: "me.",
        start: 13.24,
        end: 13.44,
      },
      {
        text: "I",
        start: 13.48,
        end: 13.6,
      },
      {
        text: "don't",
        start: 13.6,
        end: 13.72,
      },
      {
        text: "care",
        start: 13.76,
        end: 13.88,
      },
      {
        text: "how",
        start: 13.92,
        end: 14.04,
      },
      {
        text: "much",
        start: 14.08,
        end: 14.24,
      },
      {
        text: "money",
        start: 14.28,
        end: 14.44,
      },
      {
        text: "you",
        start: 14.48,
        end: 14.6,
      },
      {
        text: "make.",
        start: 14.64,
        end: 14.96,
      },
      {
        text: "You",
        start: 15.04,
        end: 15.24,
      },
      {
        text: "only",
        start: 15.28,
        end: 15.44,
      },
      {
        text: "get",
        start: 15.48,
        end: 15.68,
      },
      {
        text: "24",
        start: 15.72,
        end: 16.12,
      },
      {
        text: "hours",
        start: 16.16,
        end: 16.32,
      },
      {
        text: "in",
        start: 16.36,
        end: 16.48,
      },
      {
        text: "a",
        start: 16.48,
        end: 16.6,
      },
      {
        text: "day.",
        start: 16.64,
        end: 16.88,
      },
      {
        text: "And",
        start: 16.92,
        end: 17.08,
      },
      {
        text: "the",
        start: 17.12,
        end: 17.24,
      },
      {
        text: "difference",
        start: 17.28,
        end: 17.52,
      },
      {
        text: "between",
        start: 17.56,
        end: 17.92,
      },
      {
        text: "Oprah",
        start: 18,
        end: 18.56,
      },
      {
        text: "and",
        start: 18.6,
        end: 18.76,
      },
      {
        text: "the",
        start: 18.8,
        end: 18.92,
      },
      {
        text: "person",
        start: 18.96,
        end: 19.2,
      },
      {
        text: "that's",
        start: 19.24,
        end: 19.48,
      },
      {
        text: "broke",
        start: 19.52,
        end: 20.12,
      },
      {
        text: "is",
        start: 20.2,
        end: 20.56,
      },
      {
        text: "oprah",
        start: 20.6,
        end: 21.08,
      },
      {
        text: "uses",
        start: 21.12,
        end: 21.44,
      },
      {
        text: "her",
        start: 21.48,
        end: 21.68,
      },
      {
        text: "24",
        start: 21.72,
        end: 22.28,
      },
      {
        text: "hours",
        start: 22.36,
        end: 22.76,
      },
      {
        text: "wisely.",
        start: 22.88,
        end: 23.88,
      },
      {
        text: "That's",
        start: 24.88,
        end: 25.28,
      },
      {
        text: "it.",
        start: 25.32,
        end: 25.48,
      },
      {
        text: "Listen",
        start: 25.52,
        end: 25.72,
      },
      {
        text: "to",
        start: 25.76,
        end: 25.92,
      },
      {
        text: "me.",
        start: 25.96,
        end: 26.2,
      },
      {
        text: "That's",
        start: 26.24,
        end: 26.48,
      },
      {
        text: "it.",
        start: 26.52,
        end: 26.68,
      },
      {
        text: "You",
        start: 26.72,
        end: 26.88,
      },
      {
        text: "get",
        start: 26.92,
        end: 27.08,
      },
      {
        text: "24",
        start: 27.12,
        end: 27.84,
      },
      {
        text: "I",
        start: 27.96,
        end: 28.16,
      },
      {
        text: "don't",
        start: 28.2,
        end: 28.36,
      },
      {
        text: "care",
        start: 28.36,
        end: 28.64,
      },
      {
        text: "you",
        start: 28.72,
        end: 28.92,
      },
      {
        text: "broke.",
        start: 28.96,
        end: 29.32,
      },
      {
        text: "You",
        start: 29.36,
        end: 29.56,
      },
      {
        text: "grew",
        start: 29.6,
        end: 29.8,
      },
      {
        text: "up",
        start: 29.8,
        end: 29.92,
      },
      {
        text: "broke.",
        start: 29.96,
        end: 30.32,
      },
      {
        text: "I",
        start: 30.4,
        end: 30.56,
      },
      {
        text: "don't",
        start: 30.6,
        end: 30.76,
      },
      {
        text: "care",
        start: 30.76,
        end: 30.88,
      },
      {
        text: "if",
        start: 30.92,
        end: 31,
      },
      {
        text: "you",
        start: 31,
        end: 31.12,
      },
      {
        text: "grew",
        start: 31.16,
        end: 31.32,
      },
      {
        text: "up",
        start: 31.32,
        end: 31.48,
      },
      {
        text: "rich.",
        start: 31.52,
        end: 31.96,
      },
      {
        text: "I",
        start: 32.04,
        end: 32.24,
      },
      {
        text: "don't",
        start: 32.28,
        end: 32.44,
      },
      {
        text: "care",
        start: 32.44,
        end: 32.56,
      },
      {
        text: "if",
        start: 32.6,
        end: 32.68,
      },
      {
        text: "you're",
        start: 32.68,
        end: 32.88,
      },
      {
        text: "in",
        start: 32.92,
        end: 33.08,
      },
      {
        text: "college.",
        start: 33.12,
        end: 33.48,
      },
      {
        text: "You're",
        start: 33.56,
        end: 33.84,
      },
      {
        text: "not",
        start: 33.88,
        end: 34,
      },
      {
        text: "in",
        start: 34.04,
        end: 34.16,
      },
      {
        text: "college.",
        start: 34.2,
        end: 34.52,
      },
      {
        text: "You",
        start: 34.6,
        end: 34.8,
      },
      {
        text: "only",
        start: 34.84,
        end: 34.96,
      },
      {
        text: "get",
        start: 35,
        end: 35.16,
      },
      {
        text: "24",
        start: 35.2,
        end: 35.84,
      },
      {
        text: "hours.",
        start: 35.92,
        end: 36.32,
      },
      {
        text: "And",
        start: 36.44,
        end: 36.68,
      },
      {
        text: "I",
        start: 36.72,
        end: 37.04,
      },
      {
        text: "blew",
        start: 37.12,
        end: 37.44,
      },
      {
        text: "up.",
        start: 37.52,
        end: 37.84,
      },
      {
        text: "Literally.",
        start: 37.92,
        end: 38.64,
      },
      {
        text: "I",
        start: 38.84,
        end: 39.12,
      },
      {
        text: "went",
        start: 39.16,
        end: 39.32,
      },
      {
        text: "from",
        start: 39.36,
        end: 39.52,
      },
      {
        text: "being",
        start: 39.56,
        end: 39.72,
      },
      {
        text: "a",
        start: 39.76,
        end: 39.92,
      },
      {
        text: "high",
        start: 39.96,
        end: 40.08,
      },
      {
        text: "school",
        start: 40.12,
        end: 40.36,
      },
      {
        text: "dropout",
        start: 40.4,
        end: 41.28,
      },
      {
        text: "to",
        start: 41.48,
        end: 41.8,
      },
      {
        text: "selling",
        start: 41.84,
        end: 42.24,
      },
      {
        text: "6000",
        start: 42.28,
        end: 42.8,
      },
      {
        text: "books",
        start: 42.88,
        end: 43.16,
      },
      {
        text: "in",
        start: 43.16,
        end: 43.28,
      },
      {
        text: "less",
        start: 43.32,
        end: 43.44,
      },
      {
        text: "than",
        start: 43.48,
        end: 43.6,
      },
      {
        text: "six",
        start: 43.64,
        end: 43.8,
      },
      {
        text: "months.",
        start: 43.84,
        end: 44.04,
      },
      {
        text: "What",
        start: 44.08,
        end: 44.28,
      },
      {
        text: "happened",
        start: 44.32,
        end: 44.64,
      },
      {
        text: "in.",
        start: 44.72,
        end: 44.88,
      },
      {
        text: "My",
        start: 44.92,
        end: 45.04,
      },
      {
        text: "24",
        start: 45.08,
        end: 45.48,
      },
      {
        text: "hours?",
        start: 45.52,
        end: 46.12,
      },
      {
        text: "I",
        start: 46.48,
        end: 46.8,
      },
      {
        text: "was",
        start: 46.84,
        end: 46.96,
      },
      {
        text: "like,",
        start: 47,
        end: 47.12,
      },
      {
        text: "okay,",
        start: 47.16,
        end: 47.28,
      },
      {
        text: "Eric,",
        start: 47.32,
        end: 47.56,
      },
      {
        text: "you",
        start: 47.56,
        end: 47.64,
      },
      {
        text: "got",
        start: 47.64,
        end: 47.72,
      },
      {
        text: "to",
        start: 47.72,
        end: 47.8,
      },
      {
        text: "get",
        start: 47.8,
        end: 47.88,
      },
      {
        text: "a",
        start: 47.88,
        end: 47.96,
      },
      {
        text: "grip",
        start: 47.96,
        end: 48.16,
      },
      {
        text: "on",
        start: 48.2,
        end: 48.28,
      },
      {
        text: "your",
        start: 48.28,
        end: 48.4,
      },
      {
        text: "24",
        start: 48.44,
        end: 48.8,
      },
      {
        text: "hours,",
        start: 48.84,
        end: 48.96,
      },
      {
        text: "because",
        start: 49,
        end: 49.12,
      },
      {
        text: "you're",
        start: 49.16,
        end: 49.32,
      },
      {
        text: "about",
        start: 49.32,
        end: 49.44,
      },
      {
        text: "to.",
        start: 49.48,
        end: 49.56,
      },
      {
        text: "Be",
        start: 49.56,
        end: 49.64,
      },
      {
        text: "broke.",
        start: 49.64,
        end: 50,
      },
      {
        text: "For",
        start: 50.04,
        end: 50.2,
      },
      {
        text: "the",
        start: 50.24,
        end: 50.32,
      },
      {
        text: "rest",
        start: 50.32,
        end: 50.44,
      },
      {
        text: "of",
        start: 50.48,
        end: 50.6,
      },
      {
        text: "your",
        start: 50.64,
        end: 50.76,
      },
      {
        text: "life.",
        start: 50.8,
        end: 51.08,
      },
      {
        text: "And",
        start: 51.16,
        end: 51.44,
      },
      {
        text: "that's",
        start: 51.48,
        end: 51.68,
      },
      {
        text: "all",
        start: 51.68,
        end: 51.8,
      },
      {
        text: "I.",
        start: 51.84,
        end: 51.92,
      },
      {
        text: "Need",
        start: 51.92,
        end: 52.04,
      },
      {
        text: "you",
        start: 52.08,
        end: 52.16,
      },
      {
        text: "to",
        start: 52.16,
        end: 52.24,
      },
      {
        text: "do",
        start: 52.24,
        end: 52.36,
      },
      {
        text: "for",
        start: 52.4,
        end: 52.52,
      },
      {
        text: "me.",
        start: 52.56,
        end: 52.72,
      },
      {
        text: "I",
        start: 52.76,
        end: 52.92,
      },
      {
        text: "can",
        start: 52.96,
        end: 53.08,
      },
      {
        text: "tell",
        start: 53.12,
        end: 53.24,
      },
      {
        text: "you",
        start: 53.28,
        end: 53.44,
      },
      {
        text: "all",
        start: 53.48,
        end: 53.64,
      },
      {
        text: "about",
        start: 53.68,
        end: 53.92,
      },
      {
        text: "your.",
        start: 53.96,
        end: 54.12,
      },
      {
        text: "Life",
        start: 54.16,
        end: 54.52,
      },
      {
        text: "if",
        start: 54.64,
        end: 54.84,
      },
      {
        text: "you",
        start: 54.88,
        end: 55,
      },
      {
        text: "just",
        start: 55.04,
        end: 55.16,
      },
      {
        text: "write",
        start: 55.2,
        end: 55.48,
      },
      {
        text: "down",
        start: 55.56,
        end: 55.72,
      },
      {
        text: "your.",
        start: 55.76,
        end: 55.92,
      },
      {
        text: "24",
        start: 55.96,
        end: 56.28,
      },
      {
        text: "hours",
        start: 56.32,
        end: 56.48,
      },
      {
        text: "schedule.",
        start: 56.52,
        end: 56.84,
      },
      {
        text: "For",
        start: 56.88,
        end: 56.96,
      },
      {
        text: "me.",
        start: 56.96,
        end: 57.08,
      },
      {
        text: "You",
        start: 57.12,
        end: 57.24,
      },
      {
        text: "let",
        start: 57.28,
        end: 57.36,
      },
      {
        text: "me",
        start: 57.36,
        end: 57.48,
      },
      {
        text: "look",
        start: 57.52,
        end: 57.64,
      },
      {
        text: "at",
        start: 57.68,
        end: 57.76,
      },
      {
        text: "it.",
        start: 57.76,
        end: 57.88,
      },
      {
        text: "I",
        start: 57.92,
        end: 58.04,
      },
      {
        text: "can",
        start: 58.08,
        end: 58.2,
      },
      {
        text: "tell",
        start: 58.24,
        end: 58.32,
      },
      {
        text: "you",
        start: 58.32,
        end: 58.44,
      },
      {
        text: "where",
        start: 58.48,
        end: 58.6,
      },
      {
        text: "you're",
        start: 58.64,
        end: 58.72,
      },
      {
        text: "going.",
        start: 58.72,
        end: 58.8,
      },
      {
        text: "To",
        start: 58.8,
        end: 58.88,
      },
      {
        text: "be",
        start: 58.88,
        end: 58.96,
      },
      {
        text: "in",
        start: 58.96,
        end: 59.04,
      },
      {
        text: "five",
        start: 59.04,
        end: 59.2,
      },
      {
        text: "years.",
        start: 59.24,
        end: 59.44,
      },
      {
        text: "I",
        start: 59.48,
        end: 59.64,
      },
      {
        text: "can",
        start: 59.68,
        end: 59.76,
      },
      {
        text: "tell",
        start: 59.76,
        end: 59.88,
      },
      {
        text: "you",
        start: 59.92,
        end: 60,
      },
      {
        text: "where",
        start: 60,
        end: 60.12,
      },
      {
        text: "you're",
        start: 60.16,
        end: 60.24,
      },
      {
        text: "going",
        start: 60.24,
        end: 60.32,
      },
      {
        text: "to",
        start: 60.32,
        end: 60.4,
      },
      {
        text: "be",
        start: 60.4,
        end: 60.44,
      },
      {
        text: "in",
        start: 60.44,
        end: 60.48,
      },
      {
        text: "ten",
        start: 60.48,
        end: 60.64,
      },
      {
        text: "years.",
        start: 60.68,
        end: 60.88,
      },
      {
        text: "I",
        start: 60.92,
        end: 61.08,
      },
      {
        text: "can",
        start: 61.12,
        end: 61.2,
      },
      {
        text: "tell",
        start: 61.2,
        end: 61.28,
      },
      {
        text: "you",
        start: 61.28,
        end: 61.4,
      },
      {
        text: "where",
        start: 61.44,
        end: 61.52,
      },
      {
        text: "you're",
        start: 61.52,
        end: 61.6,
      },
      {
        text: "going",
        start: 61.6,
        end: 61.68,
      },
      {
        text: "to",
        start: 61.68,
        end: 61.76,
      },
      {
        text: "be",
        start: 61.76,
        end: 61.84,
      },
      {
        text: "in",
        start: 61.84,
        end: 61.92,
      },
      {
        text: "20",
        start: 61.92,
        end: 62.04,
      },
      {
        text: "years",
        start: 62.08,
        end: 62.2,
      },
      {
        text: "if",
        start: 62.24,
        end: 62.36,
      },
      {
        text: "you",
        start: 62.4,
        end: 62.48,
      },
      {
        text: "keep",
        start: 62.48,
        end: 62.6,
      },
      {
        text: "that",
        start: 62.64,
        end: 62.8,
      },
      {
        text: "schedule.",
        start: 62.84,
        end: 63.04,
      },
    ],
    animationType: "current-word",
    animationStyle: {
      outlineColor: {
        type: "basic",
        color: "#FFFFFFFF",
      },
      outlineWidth: 20,
    },
    scrollByPage: false,
    textStyle: {
      fontSize: 200,
      fontFamily: "Explora",
      color: {
        type: "basic",
        color: "#FFFFFFFF",
      },
      outlineColor: {
        type: "basic",
        color: "#FFFFFFFF",
      },
      outlineWidth: 20,
      fontWeight: 800,
      lineHeight: 1.2,
      textAlign: "center",
    },
    id: "mxgsi9",
    x: 0,
    y: 800,
    width: 1080,
    borderRadius: 0,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [],
  },
  {
    comp: "audiogram",
    height: 500,
    width: 1080,
    startFrom: 0,
    src: "https://remotionlambda-24lixyhuqn.s3.us-east-1.amazonaws.com/video.mp4",
    barWidth: 30,
    gap: 1,
    position: "end",
    roundness: 5,
    color: {
      type: "basic",
      color: "#FFFFFFFF",
    },
    mirror: true,
    smoothing: true,
    id: "skz7v8m",
    x: 0,
    y: 295,
    borderRadius: 0,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [],
  },
  {
    comp: "text",
    textStyle: {
      bg: {
        type: "basic",
        color: "#FFFFFFFF",
      },
      color: {
        type: "basic",
        color: "#FFFFFFFF",
      },
      fontSize: 180,
      fontFamily: "Inter",
      fontWeight: 700,
      textAlign: "center",
    },
    text: "Hello World",
    id: "m5sk14y",
    x: 0,
    y: 0,
    width: 1075,
    height: 295,
    borderRadius: 0,
    duration: 0,
    from: 0,
    rotation: 0,
    animations: [],
  },
];
