import {
  defaultAudiogramProps,
  defaultAudioProps,
  defaultDivProps,
  defaultGifProps,
  defaultImageProps,
  defaultLottieProps,
  defaultMapProps,
  defaultMockupProps,
  defaultPathProps,
  defaultProgressbarProps,
  defaultQRCodeProps,
  defaultTextProps,
  defaultTranscriptionProps,
  defaultVideoProps,
} from "../components";

export const compositions = [
  defaultAudioProps,
  defaultAudiogramProps,
  defaultDivProps,
  defaultGifProps,
  defaultImageProps,
  defaultLottieProps,
  defaultMapProps,
  defaultMockupProps,
  defaultPathProps,
  defaultProgressbarProps,
  defaultQRCodeProps,
  defaultTextProps,
  defaultTranscriptionProps,
  defaultVideoProps,
];
