import {
  defaultAudiogramProps,
  defaultAudioProps,
  defaultDivProps,
  defaultGifProps,
  defaultGraphProps,
  defaultImageProps,
  defaultLottieProps,
  defaultMapProps,
  defaultMockupProps,
  defaultPathProps,
  defaultProgressbarProps,
  defaultQRCodeProps,
  defaultTextProps,
  defaultTranscriptionProps,
  defaultVideoProps,
} from "../components";
import { defaultShape } from "../components/Shape";

export const compositions = [
  defaultAudioProps,
  defaultAudiogramProps,
  defaultDivProps,
  defaultGifProps,
  defaultGraphProps,
  defaultImageProps,
  defaultLottieProps,
  defaultMapProps,
  defaultMockupProps,
  defaultPathProps,
  defaultProgressbarProps,
  defaultQRCodeProps,
  defaultTextProps,
  defaultTranscriptionProps,
  defaultVideoProps,
  defaultShape,
];
